mediamix/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

# Create your views here.
app_name = "core"
urlpatterns = [
    path("",views.index, name="index"),
    path("sobremi",views.sobremi, name="sobremi"),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(template_name='core/register.html'), name='register'),
    path('profile', views.Profile.as_view(template_name='core/profile.html'), name='profile'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mediamix/mediamix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('peliculas/', include('peliculas.urls')),
    path('', include('core.urls')),
    # path('login/', views.LoginView.as_view(), name='login'),
    # path('', views.IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mediamix/core/models.py
from django.db import models

# Create your models here.

mediamix/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'email']
        

 
            

mediamix/core/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import CustomUserCreationForm, UserProfileForm

# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def sobremi(request):
    return render(request, 'core/sobremi.html')

class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')
    
    def get_object(self, queryset=None):
        # Esto garantiza que obtienes el objeto correcto (el usuario actual).
        return self.request.user

mediamix/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>MediaMix</title>
    <style>
        body, html{
            height: 100vh;
            margin: 0;
        }
        body {
    display: flex;
    flex-direction: column;
    
}

main {
    flex: 1;
}
#btn-rosa {
            color: #c8235c; /* Color del texto en blanco para buen contraste */
        }
#btn-rosa:hover {
            background-color: #f1dfe8; /* Color rosa claro */

        }
    </style>
</head>
<body>
    <!-- <header>
        <h1>
            {% block header %}   
            {% endblock header %}
        </h1>    
    </header> -->

    <main>
        {% include 'core/components/navbar.html' %} 
     {% block main %}
     {% endblock main %}
    </main>


    <footer>
        {% include 'core/components/footer.html' %}
    </footer> 
   
</body>
</html>

mediamix/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block header %}
{% endblock header %}

{% block main %}
    <main class="container my-5">
        <div class="row align-items-center">
            <!-- Imagen -->
            <div class="col-md-6 text-center mb-4 mb-md-0">
                <img src="{% static 'core/img/mediamix1.png' %}" 
                     alt="Mediamix"
                     class="img-fluid"
                     style="max-width: 80%; height: auto;">
            </div>
            <!-- Texto -->
            <div class="col-md-6">
                <h2 class="display-6 color">¡Bienvenido a Media <span class=" display-6  mix">Mix!</span></h2>
                <p class="lead">Para disfrutar de todas nuestras funciones, primero regístrate. Una vez que seas usuario, podrás:</p>
                <ul class="list-unstyled">
                    <li><strong>1. Guardar Películas:</strong> Añade tus títulos favoritos a tu lista personal con un solo clic.</li>
                    <li><strong>2. Eliminar Películas:</strong> Mantén tu colección actualizada eliminando las películas que ya no te interesan.</li>
                    <li><strong>3. Ver Películas:</strong> Accede a tu lista y reproduce cualquier película guardada desde tu perfil.</li>
                </ul>
                {% if user.is_authenticated %}
                {% else %}
                <p><strong>¡<a class="color" href="{% url 'core:register' %}"> Regístrate ahora</a>
                    y empieza a disfrutar de MediaMix!</strong></p>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock main %}

mediamix/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block header %}
{% endblock header %}

{% block main %}
    <div class="container">
        <h2 class="text-center my-4 mb-12">Log in</h2>   
        <div class="row justify-content-center" style="margin-top: 100px;">
            <div class="col-md-6">
                <div class="card">
                    
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <table>
                                {{ form.as_table }}
                            </table>   
                            </div>
                            <div class="form-group text-center">
                                <button type="submit"  id="btn-rosa"class="m-4 btn active">Iniciar Sesión</button>
                            </div>
                        </form>
                        <div class="text-center">
                            <p>No tienes una cuenta? <a  id="btn-rosa" href="{% url 'core:register' %}" class="btn btn-link">Registrarse</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

mediamix/core/templates/core/logout.html
{% extends 'core/base.html' %}
{% block header %}
    Logout
{% endblock header %}
{% block main %}
<div class="container m-4">

    <p>Has cerrado sesión</p>

        <a  class="btn btn-secondary  btn-sm" type="submit" href="{% url 'core:index' %}">volver</a>
  
</div>
{% endblock main %}

mediamix/core/templates/core/profile.html
{% extends 'core/base.html' %}
{% block header %}
    Actualizar perfil del usuario
{% endblock header %}
{% block main %}
<h2 class="text-center my-4 mb-12">Perfil</h2>   
  
        <div class="container" >
            <div class="row justify-content-center" style="margin-top: 100px;">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <table>
                                    {{ form.as_table }}
                                </table>
                                <div class="form-group text-center">
                                <button type="submit" type="submit"  id="btn-rosa"class="m-4 btn active">Registrarse</button>
                                </div>
                            </form>
    
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
{% endblock main %}

mediamix/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block header %}
{% endblock header %}

{% block main %}
    <div class="container">
        <h2 class="text-center my-4 mb-12">Nuevo ingreso</h2>   
        <div class="row justify-content-center" style="margin-top: 100px;">
            <div class="col-md-6">
                <div class="card">
                    
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <table>
                                {{ form.as_table }}
                            </table>   
                            </div>
                            <div class="form-group text-center">
                                <button type="submit"  id="btn-rosa"class="m-4 btn active">Registrarse</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

mediamix/core/templates/core/sobremi.html
{% extends 'core/base.html' %}
{% load static %}
{% block header %}
{% endblock header %}
{% block main %}
<div class="container mt-5">
    <div class="row align-items-center">
        <!-- Imagen -->
        <div class="col-md-6 text-center mb-4 mb-md-0">
            <img src="{% static 'core/img/yo.jpeg' %}" 
                 alt="Florencia Belén Montani"
                 class="img-fluid "
                 style="max-width: 50%; height: auto;">
        </div>
        <!-- Texto -->
        <div class="col-md-6">
            <h2 class="mb-4">Sobre mí</h2>
            <p class="lead">Mi nombre es Florencia Belén Montani y estoy trabajando en Globant durante 2 años y medio. Tengo un amplio conocimiento en herramientas como Google Analytics (migración de Universal a Google Analytics 4), Google Tag Manager (JavaScript), Big Query (SQL legacy), Colab (Python) y Looker (Dashboard tool).</p>

            <p class="lead">Además de mi experiencia en JavaScript, HTML, CSS y MySQL, tengo un título en Relaciones Públicas de UADE. Después de terminar mi carrera en 2019, hice una maestría en Marketing Digital. Luego decidí estudiar programación y diseño web en Da Vinci, lo que me brindó un sólido conocimiento en frontend. <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/florencia-bel%C3%A9n-montani-94bb91150/" class="color">Conoceme!</a>

{% endblock main %}