mediamix/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

# Create your views here.
app_name = "core"
urlpatterns = [
    path("",views.index, name="index"),
    path("sobremi",views.sobremi, name="sobremi"),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(template_name='core/register.html'), name='register'),
    path('profile', views.Profile.as_view(template_name='core/profile.html'), name='profile'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mediamix/mediamix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('peliculas/', include('peliculas.urls')),
    path('', include('core.urls')),
    # path('login/', views.LoginView.as_view(), name='login'),
    # path('', views.IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mediamix/peliculas/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "peliculas"


urlpatterns = [
    path("", views.index, name="index"),
    path("peliculas/list", views.PeliculaList.as_view(), name="peliculas_list"),
    path("peliculas/create", views.PeliculaCreate.as_view(), name="peliculas_create"),
    path("director/list", views.DirectorList.as_view(), name="director_list"),
    path("peliculas/detail/<int:pk>", views.PeliculaDetail.as_view(), name="peliculas_detail"),
    path("director/detail/<int:pk>", views.DirectorDetail.as_view(), name="director_detail"),
    path("peliculas/update/<int:pk>", views.PeliculaUpdate.as_view(), name="peliculas_update"),
    path("peliculas/delete/<int:pk>", views.PeliculaDelete.as_view(), name="peliculas_delete"),

    ]

mediamix/core/models.py
from django.db import models

# Create your models here.

mediamix/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'email']
        

 
            

mediamix/core/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import CustomUserCreationForm, UserProfileForm

# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def sobremi(request):
    return render(request, 'core/sobremi.html')

class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')
    
    def get_object(self, queryset=None):
        # Esto garantiza que obtienes el objeto correcto (el usuario actual).
        return self.request.user

mediamix/core/templates/core/components/buscador.html
<h2 class="text-center my-4 mb-12">
    Películas

</h2>
<div class="container-fluid mt-4">
    <form class="d-flex align-items-center mb-4" role="search" 
          action="{% if 'pelicula' in request.path %}{% url 'peliculas:peliculas_list' %}{% else %}{% url 'peliculas:director_list' %}{% endif %}" 
          method="get">
        <input class="form-control me-2" style="max-width: 250px;" type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q }}">
        
        <button type="submit" class="btn btn-outline-success me-2">Buscar</button>
    </form>
</div>

mediamix/core/templates/core/components/footer.html
<footer id="footer"class=" text-center py-3 mt-auto">
    <div class="container">
        <p class="mb-0">Hecho en el 2024 por <strong>Florencia Belén Montani</strong>, Coder House</p>
    </div>
</footer>
<style>

        #footer {
            background-color: #f1dfe8; /* Color rosa claro */
           
    }
    

</style>

mediamix/core/templates/core/components/navbar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MediaMix</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Moderustic:wght@300..800&display=swap" rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-expand-lg nav">
        <a class="navbar-brand color" href="{% url 'core:index' %}">Media <span class="mix">Mix</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:sobremi' %}">Sobre Mi</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'peliculas:index' %}">Películas</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'peliculas:director_list' %}" class="nav-link">Directores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:profile' %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'core:logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link nav-link">Log out</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Contenido principal -->
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <style>
        .nav {
            background-color: #f1dfe8; /* Color rosa claro */
            flex: 1;
        }
        .navbar-brand {
            font-family: "Moderustic", sans-serif;
            font-optical-sizing: auto;
            font-style: normal;
        }
        .color {
            color: #ff007f; 
        }
        .mix {
            color: #ee6c08; 
        }
        .navbar-brand:hover {
            color: #e60073; /* Color rosa más oscuro al pasar el ratón */
        }
    </style>
</body>
</html>