mediamix/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

# Create your views here.
app_name = "core"
urlpatterns = [
    path("",views.index, name="index"),
    path("sobremi",views.sobremi, name="sobremi"),
    path('login', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register', views.Register.as_view(template_name='core/register.html'), name='register'),
    path('profile', views.Profile.as_view(template_name='core/profile.html'), name='profile'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mediamix/mediamix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('peliculas/', include('peliculas.urls')),
    path('', include('core.urls')),
    # path('login/', views.LoginView.as_view(), name='login'),
    # path('', views.IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mediamix/peliculas/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "peliculas"


urlpatterns = [
    path("", views.index, name="index"),
    path("peliculas/list", views.PeliculaList.as_view(), name="peliculas_list"),
    path("peliculas/create", views.PeliculaCreate.as_view(), name="peliculas_create"),
    path("director/list", views.DirectorList.as_view(), name="director_list"),
    path("peliculas/detail/<int:pk>", views.PeliculaDetail.as_view(), name="peliculas_detail"),
    path("director/detail/<int:pk>", views.DirectorDetail.as_view(), name="director_detail"),
    path("peliculas/update/<int:pk>", views.PeliculaUpdate.as_view(), name="peliculas_update"),
    path("peliculas/delete/<int:pk>", views.PeliculaDelete.as_view(), name="peliculas_delete"),

    ]

mediamix/peliculas/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError

# Create your models here.
class Director(models.Model):
    nombre = models.CharField(max_length=50,unique=True)
    biografia =  models.TextField(blank=True,null=True, verbose_name = 'biografía')

    def __str__(self):
        return self.nombre
    @property
    def peliculas(self):
        return self.peliculas_director.all()
    
    class Meta:
        verbose_name = 'Director'
        verbose_name_plural = 'Directores'
    
class Genero(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.nombre
    class Meta:
        verbose_name = 'Género'
        verbose_name_plural = 'Generos'
        
class Peliculas(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    descripcion =  models.TextField(blank=True,null=True,  verbose_name = 'descripción')
    raiting = models.FloatField(blank=True,null=True,validators=[
            MinValueValidator(1.0), 
            MaxValueValidator(10.0)
        ])
    estreno = models.DateField(null=True, blank=True)
    director_origen_id = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True, blank=True, related_name='peliculas_director', verbose_name="Director")
    generos = models.ManyToManyField(Genero, related_name='peliculas')
    imagen = models.ImageField(upload_to='imagenes_peliculas/', blank=True, null=True, verbose_name='Imagen')
   
    
    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = 'Pelicula'
        verbose_name_plural = 'Peliculas'

class Premium(models.Model):
    plan = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_actualizacion = models.DateTimeField(editable=False, auto_now=True)

    def __str__(self) -> str:
        return f'{self.plan} - ${self.precio}'

    class Meta:
        verbose_name = 'Plan Premium'
        verbose_name_plural = 'Planes Premium'

    def save(self, *args, **kwargs):
        if self.precio < 0:
            raise ValidationError('El precio no puede ser negativo.')
        super().save(*args, **kwargs)

mediamix/peliculas/forms.py
#forms
from django import forms
from .models import Peliculas
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
import re

class PeliculasForm(forms.ModelForm):
    class Meta:
        model = Peliculas
        fields= "__all__"
        widgets = {'estreno':forms.DateInput(attrs={'type':'date'})}
        
    def clean_nombre(self):
        nombre: str = self.cleaned_data.get("nombre"," ")
        
    #validar que contenga letras
        if not re.match(r'^[a-zA-Z\s]+$', nombre):
            raise ValidationError("el nombre solo debe contener letras")
    #validar la long del nombre de la pelicula       
        if len(nombre)<1 or len(nombre)>20:
            raise ValidationError('el Nombre de la película debe ser mayor a 1 letra pero menor a 20 letras.')
        return nombre
    
    def clean_raiting(self):
        raiting = self.cleaned_data.get("raiting")
        
        # Validar que el raiting esté entre 1 y 10
        if raiting is not None:
            if raiting < 1 or raiting > 10:
                raise ValidationError('El raiting debe estar entre 1 y 10.')
        
        return raiting

mediamix/peliculas/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from .models import Peliculas, Director
from .forms import PeliculasForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def index(request):
    return render(request,'peliculas/index.html')



#PELICULAS

#List
class PeliculaList(LoginRequiredMixin,ListView):
    model = Peliculas
    context_object_name = 'peliculas'
    def get_queryset(self):
        queryset =  super().get_queryset() #Peliculas.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset = Peliculas.objects.filter(nombre__icontains=query)
        return queryset  
      
#Create
class PeliculaCreate(LoginRequiredMixin,CreateView):
    model = Peliculas
    form_class = PeliculasForm
    template_name = 'peliculas/peliculas_create.html'
    success_url = reverse_lazy('peliculas:peliculas_list')


#Detail
class PeliculaDetail(LoginRequiredMixin,DetailView):
    model = Peliculas


#Update
class PeliculaUpdate(LoginRequiredMixin,UpdateView):
    model = Peliculas
    form_class = PeliculasForm
    template_name = 'peliculas/peliculas_create.html'
    success_url = reverse_lazy('peliculas:peliculas_list')
  

#Delete    
class PeliculaDelete(LoginRequiredMixin,DeleteView):
    model = Peliculas
    success_url = reverse_lazy('peliculas:peliculas_list')


# DIRECTOR

# create "create","update", delete.
#List
class DirectorList(LoginRequiredMixin,ListView):
    model = Director
    context_object_name = 'director'
 
    def get_queryset(self):
        queryset =  super().get_queryset() #Director.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset = Director.objects.filter(nombre__icontains=query)
        return queryset  
    
#Details
class DirectorDetail(LoginRequiredMixin,DetailView):
    model = Director

mediamix/peliculas/templates/peliculas/director_detail.html
{% extends 'core/base.html' %}

{% block header %}
    Director
{% endblock header %}

{% block main %}
<div class="container mt-4">
    <div class="card mx-auto" style="max-width: 600px;">
        <div class="card-body text-center">
            <h5 class="card-title">Detalles del director</h5>  
            <ul class="list-unstyled">
                <li><strong>{{ object.nombre }}</strong></li>
                <li>Películas dirigidas:</li>
                {% for pelicula in object.peliculas_director.all %}
                <li>{{ pelicula.nombre}}</li>
                {% empty %}
                <li>No hay películas dirigidas.</li>
            {% endfor %}
            <br>
            <li>
                <strong>Bigrafía:</strong>
                {% if object.biografia %}
                {{ object.biografia }}
                {% else %}
                    <p>No disponible</p>
                {% endif %}
            </li>
            </ul> 
  
            
        </div>
    </div>
</div>
<div class="mt-4 text-center"> 

    <a  class="btn btn-outline-secondary" href="{% url 'peliculas:director_list' %}">Volver </a>
</div>
{% endblock main %}

mediamix/peliculas/templates/peliculas/director_list.html
{%extends 'core/base.html'%}
{% block header %}
{% endblock header %}
{% block main %}
<h2 class="text-center my-4 mb-12">
    Directores
</h2>
<div class="container-fluid mt-4">

    <form action="{% url 'peliculas:director_list' %}" method="get">
        <input type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q }}">
        <button class="btn btn-outline-success me-2" type="submit">Buscar</button>
    </form>
</div>





<div class=" m-4 mb-12">
    <div class="list-group-item">
        {% for o in director %}
            <h3>{{ o }}</h3>
            <br>
            <div>

                <a id="btn-rosa" class="btn btn-outline btn-sm active" href="{% url 'peliculas:director_detail' o.id %}">Más información</a>       
            </div>
        {% endfor %}

    </div>

    <div class="mt-4">
        <a class="btn btn-secondary" href="{% url 'peliculas:index' %}">Volver</a>
    </div>
</div>
    

{% endblock main %}

mediamix/peliculas/templates/peliculas/index.html
{%extends 'core/base.html'%}
{% block header %}
{% endblock header %}
{% block main %}
<h2 class="text-center my-4 mb-12">Películas</h2>
<div class="container text-center">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <a href="{% url 'peliculas:peliculas_list' %}" id="btn-rosa"class="  btn active m-4">Listar películas</a>
            <p class="card-text">Listá todas las películas y hacé click para ver más información</p>
        </div>
        <div class="col-md-4 mb">
            <a href="{% url 'peliculas:peliculas_create' %}"id="btn-rosa"class=" m-4  btn active">Crear película</a>
            <p>Agregá tus películas favoritas, no olvides agregar toda la información relevante como director, fecha de estreno y raiting.</p>
        </div>
        <div class="col-md-4 mb">
          <a href="{% url 'peliculas:director_list' %}" id="btn-rosa"class="m-4 btn active">Listar directores</a>
          <p>Ingresá a ver los directores de las películas, podes leer su biografía!</p>

        </div>
        
    </div>
</div>

 

{% endblock main %}

mediamix/peliculas/templates/peliculas/peliculas_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
    <h1 class="mt-4 text-center">Películas: Borrar película</h1>
{% endblock header %}

{% block main %}
<div class="container mt-4 text-center">
    <p class="lead">¿Estás seguro que querés borrar "<strong>{{ object.nombre }}</strong>"?</p>
    <form action="" method="post" class="mb-4">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-sm">Confirmo</button>
    </form>
    <div>
        <a class="btn btn-secondary  btn-sm" href="{% url 'peliculas:peliculas_list' %}">Volver</a>
    </div>
</div>
{% endblock main %}

mediamix/peliculas/templates/peliculas/peliculas_create.html
{% extends 'core/base.html' %}

{% block header %}
    <h1 class="mt-4 text-center">
        {% if form.instance.pk %}
            Películas: Actualizar información
        {% else %}
            Películas: Agregar información
        {% endif %}
    </h1>
{% endblock header %}

{% block main %}
<div class="container mt-4">
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <button type="submit" id="btn-rosa" class="m-4 btn active">Enviar</button>
    </form>
    <div class="mt-4 text-center">
        <a class="btn btn-secondary" href="{% url 'peliculas:index' %}">Volver</a>
    </div>
</div>
{% endblock main %}

mediamix/peliculas/templates/peliculas/peliculas_detail.html
{% extends 'core/base.html' %}

{% block header %}
    <h1 class="mt-4 text-center">{{ object.nombre }}</h1>
{% endblock header %}

{% block main %}
<div class="container mt-4">
    <div class="card mx-auto" style="max-width: 600px;">
        <div class="card-body text-center">
            <h5 class="card-title">Detalles de la Película</h5>
            <ul class="list-unstyled">
                <li><strong>Nombre:</strong> {{ object.nombre }}</li>
                <br>
                <li>
                    <strong>Imagen:</strong>
                    <div class="mt-2">
                        {% if object.imagen %}
                        <img src="{{ object.imagen.url }}" alt="Imagen de {{ object.nombre }}" class="img-fluid" style="max-width: 200px;" />
                        {% else %}
                        <p>No disponible</p>
                        {% endif %}
                    </div>
                    <br>
                </li>
                <li><strong>Descripción:</strong> {{ object.descripcion }}</li>
                <li>
                    <strong>Raiting:</strong>

                        {% if object.raiting %}
                        {{ object.raiting }}
                        {% else %}
                            <p>No disponible</p>
                        {% endif %}
                </li>
                <br>
           
                <li>
                <strong>Género:</strong>
                {% if object.generos.all %}
                    {% for genero in object.generos.all %}
                        {{ genero.nombre }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                {% else %}
                    No asignado
                {% endif %}
                </li>
            </ul>
            <p>
                <strong>Director:</strong>
                {% if object.director_origen_id %}
                    {{ object.director_origen_id }}
                {% else %}
                    Sin registro de director
                {% endif %}
            </p>
        </div>
    </div>

    <div class="mt-4 text-center">
        <a class="btn btn-outline-secondary" href="{% url 'peliculas:peliculas_list' %}">Volver</a>
        <a id="btn-rosa" class="m-4 btn active" href="{% url 'peliculas:peliculas_create' %}">Crear Película</a>

    </div>
</div>
{% endblock main %}

mediamix/peliculas/templates/peliculas/peliculas_list.html
{% extends 'core/base.html' %}

{% block header %}
{% endblock header %}

{% block main %}
{% include 'core/components/buscador.html' %}
<a id="btn-rosa" class="m-4 btn active" href="{% url 'peliculas:peliculas_create' %}">Crear Película</a>


<div class=" m-4 mb-12">

    {% if peliculas %}
        <div class="list-group">
            {% for p in peliculas %}
                <div class="list-group-item">
                    <h3>{{ p.nombre }}</h3>
                    <div>
                        <a id="btn-rosa" class="btn btn-outline btn-sm active" href="{% url 'peliculas:peliculas_detail' p.id %}">Más información</a>
                        <a id="btn-rosa" class="btn btn-outline btn-sm active" href="{% url 'peliculas:peliculas_update' p.id %}">Modificar</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'peliculas:peliculas_delete' p.id %}">Borrar</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No encontrado</p>
    {% endif %}
    
    <div class="mt-4">
        <a class="btn btn-secondary" href="{% url 'peliculas:index' %}">Volver</a>
    </div>
</div>
</div>
{% endblock main %}